replicaCount: 1

image:
  repository: bitnami/redis
  tag: latest
  pullPolicy: IfNotPresent

redis:
  port: 6379
  aofEnabled: "yes"

service:
  type: ClusterIP
  port: 6379

auth:
  # Для тестового задания допустимо.
  # В production пароль не следует хранить в Git в открытом виде.
  password: password123

  # Если Secret уже существует, можно указать его здесь.
  existingSecret: ""
  existingSecretKey: redis-password

persistence:
  enabled: false
  size: 1Gi
  accessModes:
    - ReadWriteOnce

  # Пустое значение означает использование default StorageClass.
  storageClass: ""

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 256Mi

podSecurityContext:
  fsGroup: 1001

containerSecurityContext:
  runAsNonRoot: true
  runAsUser: 1001
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

startupProbe:
  enabled: true
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 30

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

livenessProbe:
  enabled: true
  initialDelaySeconds: 15
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3

hostPath:
  enabled: true
  path: /home/dmitry/redis-hostpath
  type: Directory
  mountPath: /mnt/hostpath  