{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.existingSecretKey }}: {{ required "auth.password must be specified" .Values.auth.password | b64enc | quote }}
{{- end }}